import { JetBrains_Mono as JetBrainsMonoFont } from "next/font/google";
import "./globals.css";

//components
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";

// Pastikan bahwa pemanggilan pemuat font dilakukan di scope modul dan diberikan ke konstanta.
const jetBrainsMono = JetBrainsMonoFont({ 
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-jetbrainsMono'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetBrainsMono.variable}>
        <Header />
        <StairTransition />
        <PageTransition>

        {children}
        </PageTransition>
      </body>
    </html>
  );
}

